// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV3m7I8MWvXH5P3lOJDA9XqKe_yTW_EbQ',
    appId: '1:233214328613:web:acb3165cfbc6958f5f24cc',
    messagingSenderId: '233214328613',
    projectId: 'test-vl-app',
    authDomain: 'test-vl-app.firebaseapp.com',
    storageBucket: 'test-vl-app.firebasestorage.app',
    measurementId: 'G-RSJ7QVVP3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUtDxp4fL1CJHWMldsxuSBEQKtSCkA8m4',
    appId: '1:233214328613:android:b50160236c3099c75f24cc',
    messagingSenderId: '233214328613',
    projectId: 'test-vl-app',
    storageBucket: 'test-vl-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTB2y92HjfLNUxOznS1dR05bbeeb9E-fc',
    appId: '1:233214328613:ios:69b0e40318bf228d5f24cc',
    messagingSenderId: '233214328613',
    projectId: 'test-vl-app',
    storageBucket: 'test-vl-app.firebasestorage.app',
    iosBundleId: 'com.example.testvlapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTB2y92HjfLNUxOznS1dR05bbeeb9E-fc',
    appId: '1:233214328613:ios:69b0e40318bf228d5f24cc',
    messagingSenderId: '233214328613',
    projectId: 'test-vl-app',
    storageBucket: 'test-vl-app.firebasestorage.app',
    iosBundleId: 'com.example.testvlapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDV3m7I8MWvXH5P3lOJDA9XqKe_yTW_EbQ',
    appId: '1:233214328613:web:a29869f2155d00955f24cc',
    messagingSenderId: '233214328613',
    projectId: 'test-vl-app',
    authDomain: 'test-vl-app.firebaseapp.com',
    storageBucket: 'test-vl-app.firebasestorage.app',
    measurementId: 'G-RVYMV52JY0',
  );
}
